version: "3.8"

services:
  front:
      build:
        context: ./front
        args:
          WORKDIR: $WORKDIR
      command: yarn start
      volumes:
        - "./front:/$WORKDIR"
      ports:
        - "$FRONT_PORT:3000"
